name: Security Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/juice-shop-secure
  IMAGE_TAG: ${{ github.sha }}

jobs:
  semgrep:
    name: SAST - Semgrp
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Semgrep
      run: semgrep scan --config p/owasp-top-ten --config p/security-audit --error .

  gitleaks:
    name: Secret Scan - Gitleaks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_ENABLE_COMMENTS: false

  build-scan-sign:
    name: Build, Scan, SBOM, Sign
    runs-on: ubuntu:latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} app/

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bkimminich/juice-shop:latest
          format: table
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Trivy scan (JSON for policy check)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: json
          output: trivy-results.json
          severity: CRITICAL,HIGH

      - name: Install Conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.56.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run Policy check
        run: conftest test trivy-results.json -p policies/

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: cyclonedx
          output: sbom-juice0shop.json
          scan-type: image

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-juice-shop
          path: sbom-juice-shop.json

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image
        run: cosign sign --yes ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


